# Generated by Django 2.2.1 on 2019-05-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190514_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number_of_child_elements',
        ),
        migrations.RemoveField(
            model_name='group',
            name='number_of_child_groups',
        ),
    ]
