# Generated by Django 2.2.1 on 2019-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190514_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='number_of_child_elements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='number_of_child_groups',
            field=models.IntegerField(default=0),
        ),
    ]
