# Generated by Django 2.2.1 on 2019-05-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20190514_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number_of_child_elements',
        ),
        migrations.RemoveField(
            model_name='group',
            name='number_of_child_groups',
        ),
        migrations.AlterField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='groups.Group'),
        ),
    ]
