# Generated by Django 2.2.1 on 2019-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='moderator_checked',
            field=models.NullBooleanField(default=None, verbose_name='Checked by moderator'),
        ),
    ]
