# Generated by Django 2.2.1 on 2019-05-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20190514_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='parent_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='groups.Group'),
            preserve_default=False,
        ),
    ]
