# Generated by Django 2.2.1 on 2019-05-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20190514_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
