# Generated by Django 2.2.1 on 2019-05-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_auto_20190514_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='moderator_checked',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
